### ISSUE TITLE
WUnderground Error - MenuItems.xml is malformed

### ISSUE THREAD

**Issue by ctgreybeard** [DaveL17/WUnderground#3]
After upgrading to 1.0.17 I received the following error and the plugin would not start:

WUnderground Error              MenuItems.xml is malformed

**Comment by ctgreybeard** [comment]
Found it.

menuitems.xml had a file date from January but the mode was 0600, when I changed it to 0644 the plugin started.

**Comment by DaveL17** [comment]
Very weird.  Thanks for reporting back.  I don't think I've changed the file for quite some time.  Like January.  👍

**Comment by ctgreybeard** [comment]
It was probably only a problem due to the unorthodox methods I maintain my systems. The files were not owned by the ID that runs the server (I need to reexamine that ...)  If they had been owned by the server's ID then 0600 would have been fine although 0644 is more permissive.

For the benefit of anyone coming across this problem, the files can be found under '/Library/Application Support/Perceptive Automation/Indigo 6'
