### ISSUE TITLE
Release 1.1.8 is tagged 1.1.7 and reports 1.1.9

### ISSUE THREAD

**Issue by ctgreybeard** [DaveL17/WUnderground#4]
The subject says it. Other than that I had a little trouble getting Indigo to install it but I suspect strongly that this was my problem and not the plugin'd problem.

But it reports to Indigo as version 1.1.9 and the tag in the release chain on Github is 1.1.7. Other than that it appears to be running fine.

Obviously purely cosmetic.

**Comment by DaveL17** [comment]
Thanks for reporting that. My oversight.

Should be v1.1.9 across the files.
