### ISSUE TITLE
[Request] Make Sunrise/Sunset times available

### ISSUE THREAD

**Issue by ctgreybeard** [DaveL17/WUnderground#5]
I have been using Control Pages to put together some panels for Indigo control and it's coming out very nicely. I can't find Sunrise and Sunset times anywhere and I know Indigo has them available. Would it be possible to make them visible through this plugin? Either the ones that Indigo is using or what WU has?

**Comment by DaveL17** [comment]
It's a good suggestion, thanks.  Weather Underground Astronomy data has the elements of it, but it's not presented as a complete object.  I'll add a to-do item to factor a complete object in the astronomy device.
