### ISSUE TITLE
Unable to decode data. Error: (Line 934  No JSON object could be decoded)

### ISSUE THREAD

**Issue by UberEclectic** [DaveL17/WUnderground#7]
Cannot refresh WU data.
FYI, I have my own API key configured, which is because I run the PWS that I'm trying to query.
WU made some changes late last year.  The plugin likely needs to be updated to match.

I haven't figured out how to set the debug level too high.  Toss me a bone on that and I'll provide more details.

This is what I have so far:
<pre>
Jun 19, 2020 at 11:22:02 AM
   WUnderground Debug              Parse weather data for device: Wunderground
   WUnderground Debug              Weather Underground URL suppressed. Set debug level to [High] to write it to the log.
   WUnderground Debug              Getting weather data for location: pws:KMIDEARB5
   WUnderground Debug              Unable to decode data. Error: (Line 934  No JSON object could be decoded)
   WUnderground Debug              Adding weather data for pws:KMIDEARB5 to Master Weather Dictionary.
   WUnderground Debug                165 callsLeft = (200 - 35)
   WUnderground Debug              Error: (Line 2386  'response')
   WUnderground Debug              Error: (Line 2403  'current_observation')
   WUnderground Status             Wunderground cannot determine age of data. Skipping until next scheduled poll.
   WUnderground Debug              Locations Polled: [u'pws:KMIDEARB5']
                                  Weather Underground cycle complete.
</pre>

**Comment by UberEclectic** [comment]
Found the debug options.  Reason I couldn't see them is the window is taller than my display resolution and I had to page-down to see them.

**Comment by UberEclectic** [comment]
Here is what curl tells me about the attempt (with API key obfuscated, here):

<pre>
* TCP_NODELAY set
* Connected to api.wunderground.com (104.87.15.192) port 80 (#0)
> GET /api/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/geolookup/alerts_v11/almanac_v11/astronomy_v11/conditions_v11/forecast_v11/forecast10day_v11/hourly_v11/lang:EN/yesterday_v11/tide_v11/q/pws:KMIDEARB5.json?apiref=XXXXXXXXXXXXXXXX HTTP/1.1
> Host: api.wunderground.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
< Server: awselb/2.0
< Content-Type: text/plain; charset=utf-8
< Content-Length: 0
< Expires: Fri, 19 Jun 2020 15:47:35 GMT
< Cache-Control: max-age=0, no-cache
< Pragma: no-cache
< Date: Fri, 19 Jun 2020 15:47:35 GMT
< Connection: keep-alive
< X-Origin-Hint: Default
</pre>

**Comment by UberEclectic** [comment]
Incidentally, this is the API that I normally use for the current observations:

<pre>
https://api.weather.com/v2/pws/observations/all/1day?stationId=KMIDEARB5&format=json&units=m&apiKey=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
</pre>

**Comment by UberEclectic** [comment]
Here is the more relevant API for just getting the current conditions:

<pre>
https://api.weather.com/v2/pws/observations/current?stationId=KMIDEARB5&format=json&units=m&apiKey=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
</pre>

**Comment by UberEclectic** [comment]
Other data can be found in the forecast API, but it doesn't go by station ID.  You would need to obtain the user's postalKey, or LAT/LONG.  The postalKey is easiest, because it's just {postal_code:country_code}, such as 48124:US in my example:

<pre>
https://api.weather.com/v3/wx/forecast/daily/5day?postalKey=48124:US&units=e&language=en-US&format=json&apiKey=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
</pre>

**Comment by UberEclectic** [comment]
API reference is over here, in case you need it:

[WU PWS API Reference](https://docs.google.com/document/d/1eKCnKXI9xnoMGRRzOL1xPCBihNV2rOet08qpE_gArAY/edit)

**Comment by howartp84** [comment]
Leon, the plugin is deprecated since the API changes.

https://forums.indigodomo.com/viewtopic.php?f=149&t=20835

**Comment by DaveL17** [comment]
Yes, that's right. Weather Underground has shut down their API service, development on this plugin has ceased, and all users were pointed to the Fantastic Weather Plugin which works with Dark Sky.  The WU plugin was deprecated in May of 2019.  

More recently, Apple bought Dark Sky and will no longer be issuing API keys.  So the Fantastic Weather plugin will also soon be deprecated.  Right now, the plan is to direct users to the GhostXML plugin (which also supports JSON).

**Comment by UberEclectic** [comment]
I did a quick and dirty re-write / strip down just to get the functionality that I needed working.
I mainly just need to know the temperature being reported by my PWS so that I can control an outdoor circuit that keeps water from freezing.

I posted the changes over here:

https://github.com/UberEclectic/WUnderground/tree/master/Wunderground.indigoPlugin/Contents

Anyone can just install the original plugin and then replace the following two files, locally:

/Library/Application Support/Perceptive Automation/Indigo {version}/Plugins/Wunderground.indigoPlugin/Contents/Info.plist
/Library/Application Support/Perceptive Automation/Indigo {version}/Plugins/Wunderground.indigoPlugin/Contents/Server Plugin/plugin.py

Must also change the  "Location" property in the UI to a valid PWS station ID, such as KMIDEARB5 in my example.

Then restart the plugin.

**Comment by DaveL17** [comment]
Glad you were able to find a solution that worked for you.

**Comment by UberEclectic** [comment]
@DaveL17 as I got super intimate with your code, I came to appreciate all the hard work you had put into it.   It's really a shame what's happened to WU since they were acquired.  I've been impacted by their incompetence left and right on the PWS side with the constant changes, breaking things left and right, EVEN under their new API.  They're the worst.  :-(   That said, if I had the motivation it would be possible to bring back a lot of the functionality that you had.  Make two calls to the current observations API, one for metric, one for "standard" and combine the results.
It wouldn't be too hard to even merge the "imperial" and "metric" arrays into a single weather_data object, just to avoid having to completely re-architect how you are doing things.
Could switch to the 5-day forecast (instead of the former 10-day) without too much work.
Could add a function to compute the N/S/E/W wind direction from the angle.
The moon phases are still available.  Unfortunately, the almanac is not.

Anyway, Kudos for what was obviously a labor of love.
Cheers!

**Comment by DaveL17** [comment]
I'd caution against putting a lot of effort in working on anything that works with WU's online API. IBM has said that they're planning to shut it down and were talking about some form of CSV download procedure for PWS owners to get access to their historical data. Of course, they'll still be happy to accept PWS data uploads.

Thanks for the kind words.  It's one of the plugins that I cut my teeth on.  I didn't know a lick of Python when development began.
